// Request get data airCraft
export const REQUEST_GET_DATA_AIRCRAFT = 'REQUEST_GET_DATA_AIRCRAFT';
export const REQUEST_GET_DATA_AIRCRAFT_SUCCESS =
  'REQUEST_GET_DATA_AIRCRAFT_SUCCESS';
export const REQUEST_GET_DATA_AIRCRAFT_FAILED =
  'REQUEST_GET_DATA_AIRCRAFT_FAILED';
